src/Entity/Ride.php
<?php

namespace App\Entity;

use App\Repository\RideRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RideRepository::class)
 */
class Ride
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $fish_number;

    /**
     * @ORM\Column(type="integer")
     */
    private $stocked_fish;

    /**
     * @ORM\ManyToOne(targetEntity=Busy::class, inversedBy="rides")
     */
    private $busy;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFishNumber(): ?int
    {
        return $this->fish_number;
    }

    public function setFishNumber(int $fish_number): self
    {
        $this->fish_number = $fish_number;

        return $this;
    }

    public function getStockedFish(): ?int
    {
        return $this->stocked_fish;
    }

    public function setStockedFish(int $stocked_fish): self
    {
        $this->stocked_fish = $stocked_fish;

        return $this;
    }

    public function getBusy(): ?busy
    {
        return $this->busy;
    }

    public function setBusy(?busy $busy): self
    {
        $this->busy = $busy;

        return $this;
    }
}

src/Form/RideType.php
<?php

namespace App\Form;

use App\Entity\Ride;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RideType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('fish_number')
            ->add('stocked_fish')
            ->add('busy')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ride::class,
        ]);
    }
}

src/Controller/RideController.php
<?php

namespace App\Controller;

use App\Entity\Ride;
use App\Form\RideType;
use App\Form\RideNewType;
use App\Repository\RideRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ride")
 */
class RideController extends AbstractController
{
    /**
     * @Route("/", name="app_ride_index", methods={"GET"})
     */
    public function index(RideRepository $rideRepository): Response
    {
        return $this->render('ride/index.html.twig', [
            'rides' => $rideRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_ride_new", methods={"GET", "POST"})
     */
    public function new(Request $request, RideRepository $rideRepository): Response
    {
        $ride = new Ride();
        $form = $this->createForm(RideNewType::class, $ride);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rideRepository->add($ride);
            return $this->redirectToRoute('app_ride_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ride/new.html.twig', [
            'ride' => $ride,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_ride_show", methods={"GET"})
     */
    public function show(Ride $ride): Response
    {
        return $this->render('ride/show.html.twig', [
            'ride' => $ride,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_ride_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Ride $ride, RideRepository $rideRepository): Response
    {
        $form = $this->createForm(RideType::class, $ride);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rideRepository->add($ride);
            return $this->redirectToRoute('app_ride_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ride/edit.html.twig', [
            'ride' => $ride,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_ride_delete", methods={"POST"})
     */
    public function delete(Request $request, Ride $ride, RideRepository $rideRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ride->getId(), $request->request->get('_token'))) {
            $rideRepository->remove($ride);
        }

        return $this->redirectToRoute('app_ride_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/ride/_delete_form.html.twig
<form method="post" action="{{ path('app_ride_delete', {'id': ride.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ride.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ride/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/ride/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ride{% endblock %}

{% block body %}
    <h1>Edit Ride</h1>

    {{ include('ride/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_ride_index') }}">back to list</a>

    {{ include('ride/_delete_form.html.twig') }}
{% endblock %}

templates/ride/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rapport des Trajets{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active"></li>
                </ol>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Trajets
                    </div>
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nombre de poissons péchés</th>
                                <th>Nombre de poissons stockés</th>
                                <th>Total</th>
                                <th>Employé</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for ride in rides %}
                                <tr>
                                    <td>{{ ride.id }}</td>
                                    <td>{{ ride.fishNumber }}</td>
                                    <td>{{ ride.stockedFish }}</td>
                                    <td>{{ ride.fishNumber +  ride.stockedFish}}</td>
                                    <td>{{ ride.busy.user.name }} {{ ride.busy.user.surname }}</td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="11">Pas de données trouvées</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    </div>
{% endblock %}

templates/ride/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un trajet{% endblock %}

{% block body %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active"></li>
                </ol>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Salariés
                    </div>
                    <div class="card-body">
                        {{ form_start(form) }}
                            Poissons péchés :
                            {{ form_widget(form.fish_number) }}
                            </br>
                            Poissons stockés :
                            {{ form_widget(form.stocked_fish) }}
                            </br>
                            <p></p>
                            <button class="btn btn-primary" type="submit">Enregistrer</button>
                            <p></p>
                        {{ form_end(form) }}
                        <a class="btn btn-danger" href="{{ path('app_ride_index') }}">Annuler</a>
                        {#{{ include('ride/_form.html.twig') }}#}
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    </div>
{% endblock %}

templates/ride/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ride{% endblock %}

{% block body %}
    <h1>Ride</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ride.id }}</td>
            </tr>
            <tr>
                <th>Fish_number</th>
                <td>{{ ride.fishNumber }}</td>
            </tr>
            <tr>
                <th>Stocked_fish</th>
                <td>{{ ride.stockedFish }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_ride_index') }}">back to list</a>

    <a href="{{ path('app_ride_edit', {'id': ride.id}) }}">edit</a>

    {{ include('ride/_delete_form.html.twig') }}
{% endblock %}