src/Entity/BusyVehicule.php
<?php

namespace App\Entity;

use App\Repository\BusyVehiculeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BusyVehiculeRepository::class)
 */
class BusyVehicule
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datetime_beggening;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datetime_end;

    /**
     * @ORM\ManyToOne(targetEntity=Vehicle::class, inversedBy="busyVehicules")
     */
    private $vehicle;

    /**
     * @ORM\ManyToOne(targetEntity=Busy::class, inversedBy="busyVehicules")
     */
    private $busy;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatetimeBeggening(): ?\DateTimeInterface
    {
        return $this->datetime_beggening;
    }

    public function setDatetimeBeggening(\DateTimeInterface $datetime_beggening): self
    {
        $this->datetime_beggening = $datetime_beggening;

        return $this;
    }

    public function getDatetimeEnd(): ?\DateTimeInterface
    {
        return $this->datetime_end;
    }

    public function setDatetimeEnd(\DateTimeInterface $datetime_end): self
    {
        $this->datetime_end = $datetime_end;

        return $this;
    }

    public function getVehicle(): ?vehicle
    {
        return $this->vehicle;
    }

    public function setVehicle(?vehicle $vehicle): self
    {
        $this->vehicle = $vehicle;

        return $this;
    }

    public function getBusy(): ?busy
    {
        return $this->busy;
    }

    public function setBusy(?busy $busy): self
    {
        $this->busy = $busy;

        return $this;
    }
}

src/Form/BusyVehiculeType.php
<?php

namespace App\Form;

use App\Entity\BusyVehicule;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BusyVehiculeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('datetime_beggening')
            ->add('datetime_end')
            ->add('vehicle')
            ->add('busy')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => BusyVehicule::class,
        ]);
    }
}

src/Controller/BusyVehiculeController.php
<?php

namespace App\Controller;

use App\Entity\BusyVehicule;
use App\Form\BusyVehiculeType;
use App\Repository\BusyVehiculeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/busy/vehicule")
 */
class BusyVehiculeController extends AbstractController
{
    /**
     * @Route("/", name="app_busy_vehicule_index", methods={"GET"})
     */
    public function index(BusyVehiculeRepository $busyVehiculeRepository): Response
    {
        return $this->render('busy_vehicule/index.html.twig', [
            'busy_vehicules' => $busyVehiculeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_busy_vehicule_new", methods={"GET", "POST"})
     */
    public function new(Request $request, BusyVehiculeRepository $busyVehiculeRepository): Response
    {
        $busyVehicule = new BusyVehicule();
        $form = $this->createForm(BusyVehiculeType::class, $busyVehicule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $busyVehiculeRepository->add($busyVehicule);
            return $this->redirectToRoute('app_busy_vehicule_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('busy_vehicule/new.html.twig', [
            'busy_vehicule' => $busyVehicule,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_busy_vehicule_show", methods={"GET"})
     */
    public function show(BusyVehicule $busyVehicule): Response
    {
        return $this->render('busy_vehicule/show.html.twig', [
            'busy_vehicule' => $busyVehicule,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_busy_vehicule_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, BusyVehicule $busyVehicule, BusyVehiculeRepository $busyVehiculeRepository): Response
    {
        $form = $this->createForm(BusyVehiculeType::class, $busyVehicule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $busyVehiculeRepository->add($busyVehicule);
            return $this->redirectToRoute('app_busy_vehicule_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('busy_vehicule/edit.html.twig', [
            'busy_vehicule' => $busyVehicule,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_busy_vehicule_delete", methods={"POST"})
     */
    public function delete(Request $request, BusyVehicule $busyVehicule, BusyVehiculeRepository $busyVehiculeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$busyVehicule->getId(), $request->request->get('_token'))) {
            $busyVehiculeRepository->remove($busyVehicule);
        }

        return $this->redirectToRoute('app_busy_vehicule_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/busy_vehicule/_delete_form.html.twig
<form method="post" action="{{ path('app_busy_vehicule_delete', {'id': busy_vehicule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ busy_vehicule.id) }}">
    <button class="btn">Delete</button>
</form>

templates/busy_vehicule/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/busy_vehicule/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit BusyVehicule{% endblock %}

{% block body %}
    <h1>Edit BusyVehicule</h1>

    {{ include('busy_vehicule/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_busy_vehicule_index') }}">back to list</a>

    {{ include('busy_vehicule/_delete_form.html.twig') }}
{% endblock %}

templates/busy_vehicule/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}BusyVehicule index{% endblock %}

{% block body %}
    <h1>BusyVehicule index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Datetime_beggening</th>
                <th>Datetime_end</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for busy_vehicule in busy_vehicules %}
            <tr>
                <td>{{ busy_vehicule.id }}</td>
                <td>{{ busy_vehicule.datetimeBeggening ? busy_vehicule.datetimeBeggening|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ busy_vehicule.datetimeEnd ? busy_vehicule.datetimeEnd|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_busy_vehicule_show', {'id': busy_vehicule.id}) }}">show</a>
                    <a href="{{ path('app_busy_vehicule_edit', {'id': busy_vehicule.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_busy_vehicule_new') }}">Create new</a>
{% endblock %}

templates/busy_vehicule/new.html.twig
{% block title %}New BusyVehicule{% endblock %}

{% block body %}
    <h1>Create new BusyVehicule</h1>

    {{ include('busy_vehicule/_form.html.twig') }}

    <a href="{{ path('app_busy_vehicule_index') }}">back to list</a>
{% endblock %}

templates/busy_vehicule/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}BusyVehicule{% endblock %}

{% block body %}
    <h1>BusyVehicule</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ busy_vehicule.id }}</td>
            </tr>
            <tr>
                <th>Datetime_beggening</th>
                <td>{{ busy_vehicule.datetimeBeggening ? busy_vehicule.datetimeBeggening|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Datetime_end</th>
                <td>{{ busy_vehicule.datetimeEnd ? busy_vehicule.datetimeEnd|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_busy_vehicule_index') }}">back to list</a>

    <a href="{{ path('app_busy_vehicule_edit', {'id': busy_vehicule.id}) }}">edit</a>

    {{ include('busy_vehicule/_delete_form.html.twig') }}
{% endblock %}