src/Entity/Vehicle.php
<?php

namespace App\Entity;

use App\Repository\VehicleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VehicleRepository::class)
 */
class Vehicle
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $registration;

    /**
     * @ORM\Column(type="float")
     */
    private $fuel_level;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_use;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\ManyToOne(targetEntity=VehicleType::class, inversedBy="vehicles")
     */
    private $vehicletype;

    /**
     * @ORM\OneToMany(targetEntity=BusyVehicule::class, mappedBy="vehicle")
     */
    private $busyVehicules;


    public function __construct()
    {
        $this->busyVehicules = new ArrayCollection();
    }

    public function __toString() : string
    {
        // TODO: Implement __toString() method.
        return $this->getRegistration() . " " . $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRegistration(): ?string
    {
        return $this->registration;
    }

    public function setRegistration(string $registration): self
    {
        $this->registration = $registration;

        return $this;
    }

    public function getFuelLevel(): ?float
    {
        return $this->fuel_level;
    }

    public function setFuelLevel(float $fuel_level): self
    {
        $this->fuel_level = $fuel_level;

        return $this;
    }

    public function getIsUse(): ?bool
    {
        return $this->is_use;
    }

    public function setIsUse(bool $is_use): self
    {
        $this->is_use = $is_use;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getVehicletype(): ?vehicletype
    {
        return $this->vehicletype;
    }

    public function setVehicletype(?vehicletype $vehicletype): self
    {
        $this->vehicletype = $vehicletype;

        return $this;
    }

    /**
     * @return Collection<int, BusyVehicule>
     */
    public function getBusyVehicules(): Collection
    {
        return $this->busyVehicules;
    }

    public function addBusyVehicule(BusyVehicule $busyVehicule): self
    {
        if (!$this->busyVehicules->contains($busyVehicule)) {
            $this->busyVehicules[] = $busyVehicule;
            $busyVehicule->setVehicle($this);
        }

        return $this;
    }

    public function removeBusyVehicule(BusyVehicule $busyVehicule): self
    {
        if ($this->busyVehicules->removeElement($busyVehicule)) {
            // set the owning side to null (unless already changed)
            if ($busyVehicule->getVehicle() === $this) {
                $busyVehicule->setVehicle(null);
            }
        }

        return $this;
    }


}

src/Entity/VehicleType.php
<?php

namespace App\Entity;

use App\Repository\VehicleTypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VehicleTypeRepository::class)
 */
class VehicleType
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $vehicle_type;

    /**
     * @ORM\OneToMany(targetEntity=Vehicle::class, mappedBy="vehicletype")
     */
    private $vehicles;

    public function __construct()
    {
        $this->vehicles = new ArrayCollection();
    }

    public function __toString() : string
    {
        // TODO: Implement __toString() method.
        return  $this->vehicle_type;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVehicleType(): ?string
    {
        return $this->vehicle_type;
    }

    public function setVehicleType(string $vehicle_type): self
    {
        $this->vehicle_type = $vehicle_type;

        return $this;
    }

    /**
     * @return Collection<int, Vehicle>
     */
    public function getVehicles(): Collection
    {
        return $this->vehicles;
    }

    public function addVehicle(Vehicle $vehicle): self
    {
        if (!$this->vehicles->contains($vehicle)) {
            $this->vehicles[] = $vehicle;
            $vehicle->setVehicletype($this);
        }

        return $this;
    }

    public function removeVehicle(Vehicle $vehicle): self
    {
        if ($this->vehicles->removeElement($vehicle)) {
            // set the owning side to null (unless already changed)
            if ($vehicle->getVehicletype() === $this) {
                $vehicle->setVehicletype(null);
            }
        }

        return $this;
    }
}

src/Form/VehicleType.php
<?php

namespace App\Form;

use App\Entity\Vehicle;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VehicleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('registration')
            ->add('fuel_level')
            ->add('Name')
            ->add('vehicletype')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vehicle::class,
        ]);
    }
}

src/Controller/VehicleController.php
<?php

namespace App\Controller;

use App\Entity\Vehicle;
use App\Form\VehicleType;
use App\Repository\VehicleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/vehicle")
 */
class VehicleController extends AbstractController
{
    /**
     * @Route("/", name="app_vehicle_index", methods={"GET"})
     */
    public function index(VehicleRepository $vehicleRepository): Response
    {
        return $this->render('vehicle/index.html.twig', [
            'vehicles' => $vehicleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_vehicle_new", methods={"GET", "POST"})
     */
    public function new(Request $request, VehicleRepository $vehicleRepository): Response
    {
        $vehicle = new Vehicle();
        $form = $this->createForm(VehicleType::class, $vehicle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $vehicleRepository->add($vehicle);
            return $this->redirectToRoute('app_vehicle_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('vehicle/new.html.twig', [
            'vehicle' => $vehicle,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_vehicle_show", methods={"GET"})
     */
    public function show(Vehicle $vehicle): Response
    {
        return $this->render('vehicle/show.html.twig', [
            'vehicle' => $vehicle,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_vehicle_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Vehicle $vehicle, VehicleRepository $vehicleRepository): Response
    {
        $form = $this->createForm(VehicleType::class, $vehicle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $vehicleRepository->add($vehicle);
            return $this->redirectToRoute('app_vehicle_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('vehicle/edit.html.twig', [
            'vehicle' => $vehicle,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_vehicle_delete", methods={"POST"})
     */
    public function delete(Request $request, Vehicle $vehicle, VehicleRepository $vehicleRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vehicle->getId(), $request->request->get('_token'))) {
            $vehicleRepository->remove($vehicle);
        }

        return $this->redirectToRoute('app_vehicle_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/vehicle/_delete_form.html.twig
<form method="post" action="{{ path('app_vehicle_delete', {'id': vehicle.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vehicle.id) }}">
    <button class="btn">Delete</button>
</form>

templates/vehicle/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/vehicle/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Vehicle{% endblock %}

{% block body %}
    <h1>Edit Vehicle</h1>

    {{ include('vehicle/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_vehicle_index') }}">back to list</a>

    {{ include('vehicle/_delete_form.html.twig') }}
{% endblock %}

templates/vehicle/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des véhicules{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active"></li>
                </ol>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Liste des Véhicules
                    </div>
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Immatriculation</th>
                                <th>Niveau de carburant</th>
                                <th>Est utilisé ?</th>
                                <th>Nom</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for vehicle in vehicles %}
                                <tr>
                                    <td>{{ vehicle.id }}</td>
                                    <td>{{ vehicle.registration }}</td>
                                    <td>{{ vehicle.fuelLevel }}</td>
                                    <td>{{ vehicle.isUse ? 'Yes' : 'No' }}</td>
                                    <td>{{ vehicle.Name }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    </div>
{% endblock %}

templates/vehicle/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un véhicule{% endblock %}

{% block body %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active"></li>
                </ol>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Ajouter un salarié
                    </div>
                    <div class="card-body">
                        {{ form_start(form) }}
                        Nom :
                        {{ form_widget(form.Name) }}
                        </br>
                        Plaque d'imatriculation :
                        {{ form_widget(form.registration) }}
                        </br>
                        Niveau de carburant :
                        {{ form_widget(form.fuel_level) }}
                        </br>
                        Type de véhicule :
                        {{ form_widget(form.vehicletype) }}
                        </br>
                        <button class="btn btn-primary" type="submit">Enregistrer</button>
                        {{ form_end(form) }}
                        <p></p>
                        <a class="btn btn-danger" href="{{ path('app_customer_index') }}">Annuler</a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    </div>
{% endblock %}

templates/vehicle/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vehicle{% endblock %}

{% block body %}
    <h1>Vehicle</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vehicle.id }}</td>
            </tr>
            <tr>
                <th>Registration</th>
                <td>{{ vehicle.registration }}</td>
            </tr>
            <tr>
                <th>Fuel_level</th>
                <td>{{ vehicle.fuelLevel }}</td>
            </tr>
            <tr>
                <th>Is_use</th>
                <td>{{ vehicle.isUse ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ vehicle.Name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_vehicle_index') }}">back to list</a>

    <a href="{{ path('app_vehicle_edit', {'id': vehicle.id}) }}">edit</a>

    {{ include('vehicle/_delete_form.html.twig') }}
{% endblock %}