src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $comment;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_busy;

    /**
     * @ORM\Column(type="date")
     */
    private $recruitment_date;

    /**
     * @ORM\OneToMany(targetEntity=Absence::class, mappedBy="user")
     */
    private $absences;

    /**
     * @ORM\OneToMany(targetEntity=Busy::class, mappedBy="user")
     */
    private $busy;

    /**
     * @ORM\OneToMany(targetEntity=Sale::class, mappedBy="user")
     */
    private $sales;

    /**
     * @ORM\OneToMany(targetEntity=Promote::class, mappedBy="user")
     */
    private $promote;

    /**
     * @ORM\OneToMany(targetEntity=Pass::class, mappedBy="user")
     */
    private $pass;

    /**
     * @ORM\OneToMany(targetEntity=Warning::class, mappedBy="user")
     */
    private $warnings;

    public function __construct()
    {
        $this->absences = new ArrayCollection();
        $this->promote = new ArrayCollection();
        $this->busy = new ArrayCollection();
        $this->sales = new ArrayCollection();
        $this->pass = new ArrayCollection();
        $this->warnings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __toString() : string
    {
        // TODO: Implement __toString() method.
        return $this->name . " " . $this->surname;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = strtoupper($name);
        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = ucfirst(strtolower($surname));

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getIsBusy(): ?bool
    {
        return $this->is_busy;
    }

    public function setIsBusy(bool $is_busy): self
    {
        $this->is_busy = $is_busy;

        return $this;
    }

    public function getRecruitmentDate(): ?\DateTimeInterface
    {
        return $this->recruitment_date;
    }

    public function setRecruitmentDate(\DateTimeInterface $recruitment_date): self
    {
        $this->recruitment_date = $recruitment_date;

        return $this;
    }

    /**
     * @return Collection<int, absence>
     */
    public function getAbsences(): Collection
    {
        return $this->absences;
    }

    public function addAbsence(absence $absence): self
    {
        if (!$this->absences->contains($absence)) {
            $this->absences[] = $absence;
            $absence->setUser($this);
        }

        return $this;
    }

    public function removeAbsence(absence $absence): self
    {
        if ($this->absences->removeElement($absence)) {
            // set the owning side to null (unless already changed)
            if ($absence->getUser() === $this) {
                $absence->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, busy>
     */
    public function getBusy(): Collection
    {
        return $this->busy;
    }

    public function addBusy(busy $busy): self
    {
        if (!$this->busy->contains($busy)) {
            $this->busy[] = $busy;
            $busy->setUser($this);
        }

        return $this;
    }

    public function removeBusy(busy $busy): self
    {
        if ($this->busy->removeElement($busy)) {
            // set the owning side to null (unless already changed)
            if ($busy->getUser() === $this) {
                $busy->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, sale>
     */
    public function getSales(): Collection
    {
        return $this->sales;
    }

    public function addSale(sale $sale): self
    {
        if (!$this->sales->contains($sale)) {
            $this->sales[] = $sale;
            $sale->setUser($this);
        }

        return $this;
    }

    public function removeSale(sale $sale): self
    {
        if ($this->sales->removeElement($sale)) {
            // set the owning side to null (unless already changed)
            if ($sale->getUser() === $this) {
                $sale->setUser(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection<int, promote>
     */
    public function getPromote(): Collection
    {
        return $this->promote;
    }

    public function addPromote(promote $promote): self
    {
        if (!$this->promote->contains($promote)) {
            $this->promote[] = $promote;
            $promote->setUser($this);
        }

        return $this;
    }

    public function removePromote(promote $promote): self
    {
        if ($this->promote->removeElement($promote)) {
            // set the owning side to null (unless already changed)
            if ($promote->getUser() === $this) {
                $promote->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, pass>
     */
    public function getPass(): Collection
    {
        return $this->pass;
    }

    public function addPass(pass $pass): self
    {
        if (!$this->pass->contains($pass)) {
            $this->pass[] = $pass;
            $pass->setUser($this);
        }

        return $this;
    }

    public function removePass(pass $pass): self
    {
        if ($this->pass->removeElement($pass)) {
            // set the owning side to null (unless already changed)
            if ($pass->getUser() === $this) {
                $pass->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Warning>
     */
    public function getWarnings(): Collection
    {
        return $this->warnings;
    }

    public function addWarning(Warning $warning): self
    {
        if (!$this->warnings->contains($warning)) {
            $this->warnings[] = $warning;
            $warning->setUser($this);
        }

        return $this;
    }

    public function removeWarning(Warning $warning): self
    {
        if ($this->warnings->removeElement($warning)) {
            // set the owning side to null (unless already changed)
            if ($warning->getUser() === $this) {
                $warning->setUser(null);
            }
        }

        return $this;
    }

}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username')
            /*->add('roles')*/
            /*->add('password')*/
            ->add('name')
            ->add('surname')
            ->add('phone_number')
            ->add('comment')
            ->add('is_busy')
            ->add('recruitment_date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="app_user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_user_new", methods={"GET", "POST"})
     */
    public function new(Request $request, UserRepository $userRepository): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user);
            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_user_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user);
            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}/delete", name="app_user_delete")
     */
    public function delete(User $user): Response
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($user);
        $em->flush();

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ride{% endblock %}

{% block body %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active"></li>
                </ol>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Salariés
                    </div>
                    <div class="card-body">
                        {{ form_start(form) }}
                            Nom d'utilisateur :
                            {{ form_widget(form.username) }}
                            </br>
                            Nom de famille :
                            {{ form_widget(form.name) }}
                            </br>
                            Prénom :
                            {{ form_widget(form.surname) }}
                            </br>
                            Numéro de téléphone :
                            {{ form_widget(form.phone_number) }}
                            </br>
                            Commentaire :
                            {{ form_widget(form.comment) }}
                            </br>

                            <button class="btn btn-primary" type="submit">Enregistrer</button>
                        {{ form_end(form) }}

                        <a class="btn btn-danger" href="{{ path('app_user_index') }}">Annuler</a>
                        {{ include('user/_delete_form.html.twig') }}
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ressources humaines{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active"></li>
                </ol>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Salariés
                    </div>
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nom d'utilistateur</th>
                                <th>Nom</th>
                                <th>Prénom</th>
                                <th>Numéro de téléphone</th>
                                <th>Commentaire</th>
                                <th>Est occupé</th>
                                <th>Date de recrutement</th>
                                <th>✍</th>
                                <th>❌</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for user in users %}
                                <tr>
                                    <td>{{ user.id }}</td>
                                    <td>{{ user.username }}</td>
                                    <td>{{ user.name }}</td>
                                    <td>{{ user.surname }}</td>
                                    <td>{{ user.phoneNumber }}</td>
                                    <td>{{ user.comment }}</td>
                                    <td>{{ user.isBusy ? 'Oui' : 'Non' }}</td>
                                    <td>{{ user.recruitmentDate ? user.recruitmentDate|date('Y-m-d') : '' }}</td>
                                    <td><a href="{{ path('app_user_edit', {'id': user.id}) }}">✍</a></td>
                                    <td><a href="{{ path('app_user_delete', {'id': user.id})}}">❌</a></td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="11">Pas de données trouvées</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    </div>
{% endblock %}

templates/user/new.html.twig
{% block body %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active"></li>
                </ol>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Ajouter un salarié
                    </div>
                    <div class="card-body">
                        {{ form_start(form) }}
                            Nom d'utilisateur :
                            {{ form_widget(form.username) }}
                            </br>
                            Nombre de poissons stockés :
                            {{ form_widget(form.name) }}
                            </br>
                            Id Busy :
                            {{ form_widget(form.busy) }}
                            </br>
                            <button class="btn btn-primary" type="submit">Enregistrer</button>
                        {{ form_end(form) }}

                        <a href="{{ path('app_user_index') }}">Annuler</a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    </div>
{% endblock %}

templates/user/show.html.twig
{#{% extends 'base.html.twig' %}#}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ user.name }}</td>
            </tr>
            <tr>
                <th>Surname</th>
                <td>{{ user.surname }}</td>
            </tr>
            <tr>
                <th>Phone_number</th>
                <td>{{ user.phoneNumber }}</td>
            </tr>
            <tr>
                <th>Comment</th>
                <td>{{ user.comment }}</td>
            </tr>
            <tr>
                <th>Is_busy</th>
                <td>{{ user.isBusy ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Recruitment_date</th>
                <td>{{ user.recruitmentDate ? user.recruitmentDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_user_index') }}">back to list</a>

    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}